version: "3.1"

services:
  nodejs:
    build: .
    container_name: nodejs
    networks:
      - jaeger
    ports:
      - 3000:3000
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - OTEL_SERVICE_NAME=nodejs
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - jaeger
    ports:
      - "16686:16686" # the jaeger ui
    expose:
      - 4317 # the OpenTelemetry collector grpc
      - 4318
      - 5778
      - 6831 # agent
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  hotrod:
    image: jaegertracing/example-hotrod:1.36
    container_name: hotrod
    command: ["all"]
    networks:
      - jaeger
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://jaeger:4318"
    links:
      - jaeger
    depends_on:
      - jaeger

networks:
  jaeger: